apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: index-certificate
  namespace: develop
spec:
  dnsNames:
    - <domain>
  secretName: index-certificate-secret
  issuerRef:
    name: index-cluster-issuer
    kind: ClusterIssuer